name: e2e-standalone-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/e2e-standalone-tests.yml'
      - 'tslib/**.ts'
      - 'tslib/**.tsx'
      - 'tslib/**/package.json'
      - 'tslib/**/package-lock.json'
      - 'standalone_app/**.ts'
      - 'standalone_app/**.tsx'
      - 'standalone_app/package.json'
      - 'standalone_app/package-lock.json'
      - 'standalone_app/tsconfig.json'
      - 'standalone_app/vite.config.js'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          uv sync --group test
          uv pip install --progress-bar off .

      - name: Build rustlib
        working-directory: rustlib
        run: wasm-pack build --target web

      - name: Build tslib
        run: make tslib

      - name: Build standalone_app
        working-directory: standalone_app
        run: |
          npm install
          npx vite build --outDir dist

      - name: Install the required browsers
        run: uv run playwright install

      - name: Run e2e tests
        run: uv run pytest e2e_tests/test_standalone
