name: Build Python distributions and create GitHub Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  github-release:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv pip install --progress-bar off wheel twine build

      - run: make python-package
      - run: uv run twine check dist/*

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          cp ./optuna_dashboard/public/bundle.js ./dist/
          cp ./optuna_dashboard/public/bundle.js.LICENSE.txt ./dist/
          gh release create ${TAGNAME} --draft dist/*
