name: Build Python distributions and publish to PyPI

on:
  release:
    types:
      - published

jobs:
  pypi:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        uv pip install --upgrade pip setuptools
        uv pip install wheel twine build

    - run: make python-package

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Temporary workaround to bypass Twine's bug with attestation support
        # See https://github.com/pypa/gh-action-pypi-publish/issues/283
        # TODO(c-bata): Once a new version of twine is released, delete this line.
        # https://github.com/pypa/twine/pull/1172 
        attestations: false
