name: tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/python-tests.yml'
      - '**.py'
      - 'pyproject.toml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          uv sync --group lint
      - run: uv run ruff check .
      - run: uv run mypy optuna_dashboard python_tests
  build-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          uv venv
          uv pip install wheel twine build
      - run: make python-package
      - run: uv run twine check dist/*
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        optuna-version: ['optuna>=3.6.0']
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Optuna ${{ matrix.optuna-version }}
        run: uv add '${{ matrix.optuna-version }}'
      - name: Install dependencies
        run: uv sync --extra plotlypy --extra optional --group test
      - name: Run python unit tests
        run: uv run pytest python_tests
  test-with-optuna-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          uv sync --extra plotlypy --extra optional --group test
          uv pip install git+https://github.com/optuna/optuna.git
      - name: Run python unit tests
        run: uv run pytest python_tests
  test-with-optuna-oldest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          uv sync --extra plotlypy --extra optional --group test
          uv add optuna==3.1.0
      - name: Run python unit tests
        run: uv run pytest python_tests
