name: python coverage

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  coverage:
    runs-on: ubuntu-latest

    # Not intended for forks.
    if: github.repository == 'optuna/optuna-dashboard'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        uv sync --extra plotlypy --extra optional --group test
        echo 'import coverage; coverage.process_startup()' > sitecustomize.py
    - name: Tests
      env:
        PYTHONPATH: .  # To invoke sitecutomize.py
        COVERAGE_PROCESS_START: .coveragerc  # https://coverage.readthedocs.io/en/6.4.1/subprocess.html
        COVERAGE_COVERAGE: yes  # https://github.com/nedbat/coveragepy/blob/65bf33fc03209ffb01bbbc0d900017614645ee7a/coverage/control.py#L255-L261
      run: |
        uv run coverage run --source=optuna_dashboard -m pytest python_tests
        uv run coverage combine
        uv run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false
